name: Release Events

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  notify:
    name: Release Notifier
    runs-on: ubuntu-latest

    steps:
      - name: Notifier
        uses: agrc/release-notifier-action@dev
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
